
services:
  motarjem-bot:
    build: .
    env_file:
      - .env
    restart: always
    networks:
      - alltogether
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.motarjem-bot.rule=Host(`${WEBHOOK_URL}`)"
      - "traefik.http.routers.motarjem-bot.entrypoints=websecure"
      - "traefik.http.routers.motarjem-bot.tls.certresolver=myresolver"

networks:
  alltogether:
    external: true
