"""add_new_columns_to_file_translation

Revision ID: ae588ad31464
Revises: 3786a416e370
Create Date: 2024-12-11 16:14:46.725192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae588ad31464'
down_revision: Union[str, None] = '3786a416e370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_translations', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('file_translations', sa.Column('total_token_used', sa.Integer(), nullable=True))
    op.add_column('file_translations', sa.Column('total_cost', sa.Double(), nullable=True))
    op.create_index(op.f('ix_file_translations_id'), 'file_translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_translations_id'), table_name='file_translations')
    op.drop_column('file_translations', 'total_cost')
    op.drop_column('file_translations', 'total_token_used')
    op.drop_column('file_translations', 'file_name')
    # ### end Alembic commands ###
