"""Added message id in filetranslation

Revision ID: e480b7ee533a
Revises: ae588ad31464
Create Date: 2024-12-12 13:48:06.537576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e480b7ee533a'
down_revision: Union[str, None] = 'ae588ad31464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_translations', sa.Column('message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_translations', 'message_id')
    # ### end Alembic commands ###
